<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-android;net10.0-ios</TargetFrameworks>
        <RootNamespace>Hybrid2D.Framework</RootNamespace>
        <AssemblyName>Hybrid2D.Framework</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <OutputType>Library</OutputType>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DefineConstants>RELEASE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedJar Include="Jars\SDLActivity.jar"/>
    </ItemGroup>

</Project>
