<Project>
    
    <PropertyGroup>
        <Version>1.0.0</Version>
        <Authors>Hybrid2D</Authors>
        <Company>Hybrid2D</Company>
        <Product>Hybrid2D.Framework</Product>
        <PackageId>Hybrid2D.Framework</PackageId>
        <Copyright>(c) 2025 - 2026 Hybrid2D</Copyright>
        <PackageTags>Hybrid2D;Framework;Game</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>Cross-platform game framework for Windows, Mac, Linux, Android, IOS, Web.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="$(SolutionDir)\Natives\Desktop\Windows\win-x64\**\*">
            <PackagePath>runtimes/win-x64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Desktop\Windows\win-arm64\**\*">
            <PackagePath>runtimes/win-arm64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Desktop\Windows\win-x86\**\*">
            <PackagePath>runtimes/win-x86/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
    </ItemGroup>
    
    <ItemGroup>
        <None Include="$(SolutionDir)\Natives\Desktop\MacOS\osx-x64\**\*">
            <PackagePath>runtimes/osx-x64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Desktop\MacOS\osx-arm64\**\*">
            <PackagePath>runtimes/osx-arm64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(SolutionDir)\Natives\Desktop\Linux\linux-x64\**\*">
            <PackagePath>runtimes/linux-x64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Desktop\Linux\linux-x86\**\*">
            <PackagePath>runtimes/linux-x86/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Desktop\Linux\linux-arm64\**\*">
            <PackagePath>runtimes/linux-arm64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Desktop\Linux\linux-arm\**\*">
            <PackagePath>runtimes/linux-arm/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
    </ItemGroup>
    
    <ItemGroup>
        <None Include="$(SolutionDir)\Natives\Mobile\IOS\SDL3_image.xcframework\**\*">
            <PackagePath>runtimes/ios/native/SDL3_image.xcframework</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Mobile\IOS\SDL3_mixer.xcframework\**\*">
            <PackagePath>runtimes/ios/native/SDL3_mixer.xcframework</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Mobile\IOS\SDL3_ttf.xcframework\**\*">
            <PackagePath>runtimes/ios/native/SDL3_ttf.xcframework</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Mobile\IOS\SDL3.xcframework\**\*">
            <PackagePath>runtimes/ios/native/SDL3.xcframework</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
    </ItemGroup>
    
    <ItemGroup>
        <None Include="$(SolutionDir)\Natives\Mobile\Android\armeabi-v7a\**\*">
            <PackagePath>runtimes/android-arm/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Mobile\Android\arm64-v8a\**\*">
            <PackagePath>runtimes/android-arm64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Mobile\Android\x86_64\**\*">
            <PackagePath>runtimes/android-x64/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
        <None Include="$(SolutionDir)\Natives\Mobile\Android\x86\**\*">
            <PackagePath>runtimes/android-x86/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(SolutionDir)\Natives\Web\**\*">
            <PackagePath>runtimes/browser/native</PackagePath>
            <Visible>false</Visible>
            <Pack>true</Pack>
        </None>
    </ItemGroup>
    
</Project>