site_name: Hybrid2D
site_description: "C# Games made simple"
site_author: "Lloyd J Howarth"
favicon: "assets/Hybrid.png"

nav:
  - Home: index.md
  - Introduction: Introduction.md
  - Cheatsheet: Cheatsheet.md
  - About: About.md
  - License: License.md

theme:
  name: material
  logo: "assets/Hybrid.png"
  favicon: "assets/Hybrid.png"
  footer: "© 2026 Hybrid2D — All rights reserved"
