<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\App\**\*.cs" Exclude="..\**\bin\**;..\**\obj\**">
            <Visible>false</Visible>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Internal\STB\Image\" />
      <Folder Include="Internal\STB\Write\" />
    </ItemGroup>

</Project>
