<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Hybrid</RootNamespace>
        <AssemblyName>Hybrid</AssemblyName>
        <Nullable>disable</Nullable>
    </PropertyGroup>
    
</Project>
