<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <ItemGroup Condition="'$(HybridPlatform)' == 'IOS'">

        <NativeReference Remove="$(MSBuildThisFileDirectory)..\..\Natives\**\*"/>
        
        <NativeReference Include="$(MSBuildThisFileDirectory)..\..\Natives\Mobile\IOS\SDL3.xcframework">
            <Visible>false</Visible>
        </NativeReference>

        <NativeReference Include="$(MSBuildThisFileDirectory)..\..\Natives\Mobile\IOS\SDL3_image.xcframework">
            <Visible>false</Visible>
        </NativeReference>

        <NativeReference Include="$(MSBuildThisFileDirectory)..\..\Natives\Mobile\IOS\SDL3_mixer.xcframework">
            <Visible>false</Visible>
        </NativeReference>

        <NativeReference Include="$(MSBuildThisFileDirectory)..\..\Natives\Mobile\IOS\SDL3_ttf.xcframework">
            <Visible>false</Visible>
        </NativeReference>
        
    </ItemGroup>

</Project>