<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>
        <WasmEmitSymbolMap>true</WasmEmitSymbolMap>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ImplicitUsings>enable</ImplicitUsings>
        <WasmBuildNative>true</WasmBuildNative>
        <NoWarn>$(NoWarn);NU5100;CS8766</NoWarn>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <RootNamespace>S8_Touch</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Content Update="wwwroot\index.html" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="wwwroot\main.js" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <NativeFileReference Remove="$(SolutionDir)\Hybrid\Natives\Web\**\*"/>
        <NativeFileReference Include="$(SolutionDir)\Hybrid\Natives\Web\**\*" Visible="false"/>
        <_WasmPInvokeModules Include="SDL" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)\App\App\App.csproj" />
    </ItemGroup>

</Project>
