<Project>
    
<!-- Settings -->
    <PropertyGroup>
        <Scheme>Android</Scheme>
        <DefineConstants>$(Scheme)</DefineConstants>
    </PropertyGroup>
    
<!-- Assets -->
    <ItemGroup>
        <AndroidAsset Include="..\..\App\Assets\**\*">
            <LogicalName>Assets/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
            <Link>.Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <Visible>false</Visible>
        </AndroidAsset>
    </ItemGroup>
    
<!-- Icon -->
    <ItemGroup>
        <AndroidResource Include="..\..\Hybrid.png" Link="Resources\drawable\Hybrid.png" />
    </ItemGroup>
    
<!-- Natives -->
    <ItemGroup>
        <EmbeddedJar Include="Jars\SDLActivity.jar">
            <Visible>false</Visible>
        </EmbeddedJar>

        <AndroidNativeLibrary Include="..\..\Natives\Android\armeabi-v7a\*.so">
            <Visible>false</Visible>
            <Abi>armeabi-v7a</Abi>
        </AndroidNativeLibrary>

        <AndroidNativeLibrary Include="..\..\Natives\Android\arm64-v8a\*.so">
            <Visible>false</Visible>
            <Abi>arm64-v8a</Abi>
        </AndroidNativeLibrary>

        <AndroidNativeLibrary Include="..\..\Natives\Android\x86_64\*.so">
            <Visible>false</Visible>
            <Abi>x86_64</Abi>
        </AndroidNativeLibrary>

        <AndroidNativeLibrary Include="..\..\Natives\Android\x86\*.so">
            <Visible>false</Visible>
            <Abi>x86</Abi>
        </AndroidNativeLibrary>
    </ItemGroup>

</Project>
