<Project>

<!-- Settings -->
    <PropertyGroup>
        <Scheme>IOS</Scheme>
        <DefineConstants>$(Scheme)</DefineConstants>
    </PropertyGroup>

<!-- Assets -->
    <ItemGroup>
        <BundleResource Include="..\..\App\Assets\**\*">
            <LogicalName>Assets/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
            <Link>.Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <Visible>false</Visible>
        </BundleResource>
    </ItemGroup>
    
<!-- Natives -->
    <ItemGroup>
        <NativeReference Include="..\..\Natives\IOS\SDL2.xcframework"/>
        <NativeReference Include="..\..\Natives\IOS\IMAGE.xcframework"/>
        <NativeReference Include="..\..\Natives\IOS\MIXER.xcframework"/>
        <NativeReference Include="..\..\Natives\IOS\TTF.xcframework"/>
    </ItemGroup>

</Project>
