<Project>

<!-- Settings -->
    <PropertyGroup>
        <Scheme>IOS</Scheme>
        <DefineConstants>$(Scheme)</DefineConstants>
    </PropertyGroup>
    
<!-- Icon -->
    <ItemGroup>
        <BundleResource Include="..\..\Hybrid.png" Link="Hybrid.png"/>
    </ItemGroup>

<!-- Assets -->
    <ItemGroup>
        <BundleResource Include="..\..\App\Assets\**\*">
            <LogicalName>Assets/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
            <Link>.Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <Visible>false</Visible>
        </BundleResource>
    </ItemGroup>
    
<!-- Natives -->
    <ItemGroup>
        <NativeReference Include="..\..\Natives\IOS\SDL3.xcframework"/>
        <NativeReference Include="..\..\Natives\IOS\SDL3_image.xcframework"/>
        <NativeReference Include="..\..\Natives\IOS\SDL3_mixer.xcframework"/>
        <NativeReference Include="..\..\Natives\IOS\SDL3_ttf.xcframework"/>
    </ItemGroup>

</Project>
