<Project>

<!-- Settings -->
    <PropertyGroup>
        <Scheme>MACOS</Scheme>
        <DefineConstants>$(Platform)</DefineConstants>
    </PropertyGroup>

<!-- Includes -->
    <ItemGroup>
        <Compile Include="..\..\Engine\**\*.cs" Exclude="..\**\bin\** ; ..\**\obj\** ; ..\**\Platform\**">
            <Link>.Engine\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>

        <Compile Include="..\..\Engine\Platform\$(Scheme)\**\*.cs">
            <Link>.Engine\Platform\$(Scheme)\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>
    </ItemGroup>

<!-- Assets -->
    <ItemGroup>
        <Content Include="..\..\Engine\Assets\**\*">
            <TargetPath>Assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>.Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>

<!-- Natives -->
    <PropertyGroup>
        <Architecture Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</Architecture>
        <Architecture Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</Architecture>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\..\Natives\MacOS\$(Architecture)\**\*.dylib">
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
    </ItemGroup>

</Project>
