<Project>
    
<!-- Settings -->
    <PropertyGroup>
        <Scheme>Web</Scheme>
        <DefineConstants>$(Scheme)</DefineConstants>
        <EmccExtraLDFlags>
            -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$autoResumeAudioContext,$dynCall
            --embed-file ../../Engine/Assets@Assets
            -sALLOW_MEMORY_GROWTH=1
        </EmccExtraLDFlags>
    </PropertyGroup>

<!-- Includes -->
    <ItemGroup>
        <Compile Include="..\..\Engine\**\*.cs" Exclude="..\**\bin\** ; ..\**\obj\** ; ..\**\Platforms\**">
            <Link>.Engine\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>

        <Compile Include="..\..\Engine\Platforms\$(Scheme)\**\*.cs">
            <Link>.Engine\Platforms\$(Scheme)\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>
    </ItemGroup>
    
<!-- Assets -->
    <ItemGroup>
        <None Include="..\..\Engine\Assets\**\*">
            <Link>.Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
    </ItemGroup>

<!-- Natives -->
    <ItemGroup>
        <NativeFileReference Include="..\..\Natives\Web\browser\**\*.a"/>
        <EmccExportedRuntimeMethod Include="setMainLoop"/>
        <EmccExportedRuntimeMethod Include="SDL"/>
    </ItemGroup>

</Project>
