<Project>
    
<!-- Settings -->
    <PropertyGroup>
        <Scheme>Web</Scheme>
        <DefineConstants>$(Scheme)</DefineConstants>

        <EmccExtraLDFlags>
            -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$autoResumeAudioContext,$dynCall
            --embed-file ../../App/Assets@Assets
            -sALLOW_MEMORY_GROWTH=1
        </EmccExtraLDFlags>
    </PropertyGroup>
    
<!-- Assets -->
    <ItemGroup>
        <None Include="..\..\App\Assets\**\*">
            <Link>.Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <Visible>false</Visible>
        </None>
    </ItemGroup>

<!-- Natives -->
    <ItemGroup>
        <NativeFileReference Include="..\..\Natives\Web\**\*.a"/>
        <EmccExportedRuntimeMethod Include="setMainLoop"/>
        <EmccExportedRuntimeMethod Include="SDL"/>
    </ItemGroup>

<!-- Web Files -->
    <ItemGroup>
        <Content Update="wwwroot\index.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\main.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
