<Project>
    
<!-- Settings -->
    <PropertyGroup>
        <Scheme>Web</Scheme>
        <DefineConstants>$(Scheme)</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <EmccExtraLDFlags>
            -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$autoResumeAudioContext,$dynCall
            --embed-file ../../Engine/Assets@Assets
            -sALLOW_MEMORY_GROWTH=1
        </EmccExtraLDFlags>
    </PropertyGroup>
    
<!-- Assets -->
    <ItemGroup>
        <None Include="..\..\Engine\Assets\**\*">
            <Link>.Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
    </ItemGroup>

<!-- Natives -->
    <ItemGroup>
        <NativeFileReference Include="..\..\Natives\Web\**\*.a"/>
        <EmccExportedRuntimeMethod Include="setMainLoop"/>
        <EmccExportedRuntimeMethod Include="SDL"/>
    </ItemGroup>

</Project>
