name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'
      description:
        description: 'Release description'
        required: true
        default: 'Release description'

permissions:
  id-token: write
  contents: read
  
jobs:
  release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Source
        run: |
          ZIP_NAME="source.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          zip -r $ZIP_NAME .

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          artifacts: ${{ env.ZIP_NAME }}
          draft: false
          prerelease: false
