name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.1'
      description:
        description: 'Description'
        required: true
        default: '0.0.1 Release'

permissions:
  contents: write

jobs:
  nuget:
    name: Build & Publish NuGet ${{ github.event.inputs.version }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build & Pack
        run: |
          dotnet workload restore
          dotnet build -c Release
          dotnet pack -c Release -p:PackageVersion=${{ github.event.inputs.version }} -o .nuget
          ls -l .nuget/

      - name: Publish Packages
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
         for pkg in .nuget/*.nupkg; do
         echo "Pushing $pkg"
#          dotnet nuget push "$pkg" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
         done

  github:
    name: GitHub Release ${{ github.event.inputs.version }}
    runs-on: windows-latest
    needs: nuget
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
