name: Build Website

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.1'

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  website:
    name: Publish Website ${{ inputs.version }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      HYBRID_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Setup MKDocs
        run: |
          pip install mkdocs mkdocs-material
          
      - name: Build Project
        run: |
          dotnet workload restore
          dotnet build -c Release

      - name: Generate Documentation
        run: |
          chmod +x .github/scripts/Website/Docs/Generate.sh
          ./.github/scripts/Website/Docs/Generate.sh

      - name: Generate Samples
        run: |
          chmod +x .github/scripts/Website/Samples/Generate.sh
          ./.github/scripts/Website/Samples/Generate.sh

      - name: Build MKDocs
        run: mkdocs build

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v4